### PR TITLE
basic messenger page

### PR DESCRIPTION
**Pull request by bote795**

### CODE REVIEW

**Comment by liorgrossman** [comment]
Hi Nicolas, thanks mate!

You mentioned that the theme is still basic? (unfinished). Can you please attach some screenshots?

Generally, I prefer not to merge boilerplate themes (themes with 5 CSS selectors) into master, but prefer to merge themes when they are more mature and complete.

You can commit more changes to this pull request. Once you feel the theme is complete, please let me know and I'll merge it into master.

Thanks! 👍

**Comment by bote795** [comment]
[https://gyazo.com/a76b5ba7f5632956244161f445dbab25](https://gyazo.com/a76b5ba7f5632956244161f445dbab25)
[https://gyazo.com/e6ae788eeb3900d3a8e4930579bd719b](https://gyazo.com/e6ae788eeb3900d3a8e4930579bd719b)
and sure, I just didn't see much things to change.. as compared to other websites.

**Comment by bote795** [comment]
ur message:
[https://gyazo.com/2bfc8f46c5edce9347f7a2d6be166d4c](https://gyazo.com/2bfc8f46c5edce9347f7a2d6be166d4c)

video handling:
[https://gyazo.com/f0a59f193e0914e4acdb638e334e166b](https://gyazo.com/f0a59f193e0914e4acdb638e334e166b)

if there is something else u think i shld fix before getting added let me knw!
thx

**Comment by bote795** [comment]
did some other basic changes i think looks better now:
[https://gyazo.com/2d096d72f809553ea2b0bf23d6c3f6b0](https://gyazo.com/2d096d72f809553ea2b0bf23d6c3f6b0)

**Comment by bote795** [comment]
@liorgrossman i believe that is complete

**Comment by liorgrossman** [comment]
Looking really good according to the screenshots! Awesome work.
I'll pull and merge this once I have my computer back :)

**Comment by liorgrossman** [comment]
Hey Nicolas, I just pushed some additional fixes to the skin... Please pull
* Positioning of Darkness icon (making room in the right side of the toolbar)
* Making all the toolbar icons blue (inverting back from orange)
* Making that small Messenger icon next to avatars blue instead of orange
* Fixing the chat bubbles so they don't create background around avatars (e.g. big like button, big smile, etc.)

**Pull request merged**
