### PR TITLE
Fixes :)

### PR DESCRIPTION
**Pull request by theme1256**

### CODE REVIEW

**Comment by liorgrossman** [comment]
Just noticed the GitHub header problem yesterday, Thank you!

BTW - do you see YouTube correctly with Darkness?
Have you been upgraded to the new YouTube design? (https://www.youtube.com/new)

**Comment by theme1256** [comment]
I'm using the new design with the build in dark theme, so.... :P

**Comment by liorgrossman** [comment]
Yeah, their new dark theme is pretty darn good.
I'm working on making the 5 Darkness color themes work with the new YouTube as well.

Still trying to figure out how to programmatically **force** YouTube to **enable** their Dark theme, so I can simply overwrite the colors of links etc.
No success so far, let me know if you have any idea how to do that programmatically (JS/CSS).

**Comment by liorgrossman** [comment]
Theis, I've made an update to Darkness so now it uses YouTube's Dark Theme as a basis for Darkness Theme (significant change, including page.js and background.js)
This means that you get Google's Dark Theme, with the ability to apply Darkness colors over it (Iceberg, Material, Dusk, etc.)

Please pull and compile to get the latest skins:
git checkout master
git pull upstream master
npm install

**Pull request merged**
