### PR TITLE
New themes and some fixes

### PR DESCRIPTION
**Pull request by theme1256**
Here is a new theme for twitter and sharelatex.
I also added a couple of site where it will ask for devs.
Small fixes for the youtube theme.

### CODE REVIEW

**Comment by liorgrossman** [comment]
Awesome - thanks Theis!
Will go over the code within a day or two and merge it into master.

**Comment by Gmuela** [comment]
I copied the code to try it, but Twitter doesn't work. Did this work on your browser?

**Comment by theme1256** [comment]
Sorry, got a bit ahead of myself there.
The site is done, but lior still needs to test it, it will probably be up
in a couple of days :)

**Comment by liorgrossman** [comment]
Amazing work 👍 
Merged into master, and even added some improvements to the Twitter theme.
Please pull

**Pull request merged**
