### PR TITLE
PayPal theme, wikipedia fixes and theme names.

### PR DESCRIPTION
**Pull request by reveur404**
PayPal's bugs are written in websites/paypal.scss file.

### CODE REVIEW

**Comment by liorgrossman** [comment]
Thanks @reveur404 !
Awesome - a theme for PayPal!
And so weird we didn't notice the theme names in the SASS.

Everything looks perfect.
One comment though - can you explain why the change in packages.json is necessary?

**Comment by reveur404** [comment]
> Thanks @reveur404 !
> Awesome - a theme for PayPal!
> And so weird we didn't notice the theme names in the SASS.
> 
> Everything looks perfect.
> One comment though - can you explain why the change in packages.json is necessary?

Thank you!

So i had this error without my changes:
`AssertionError [ERR_ASSERTION]: Task function must be specified at Gulp.set [as _setTask]`

But I changed it to default again and now everything works perfect, so that's unnecessary i guess.

**Comment by reveur404** [comment]
All of my changes:

Theme names:
- known

Wikipedia: 
- syntax (semicolons),
- more visible border especially when using "Red Alert" theme on boxes like "Read", "View source", "View history"

When it comes to PayPal, there are a lot of language-based versions of the website and it's pretty hard to "darkify" all of them and make them all look perfect in the same time. Some classes and ids are overlapping each other so when I try to make a specific section of the page to black, it's black for example only on .com/us, /de, /ru, but on /pl, /es, /uk etc. it's white. So this is something that can't be fixed, but I know that most of the paypal's users won't reach those "bugged" pages. They will just simply go to the homepage, sign-in or sign-up, login to their account and that's it. **These, and 90% more sites are looking perfect**, so you won't see any white sections in there.

**Comment by liorgrossman** [comment]
Just saw the latest update, thanks!
Great work on the PayPal theme. We never reach perfect 100% coverage for most modern websites, as they are complicated, but you gotta start somewhere :)
Thanks for the other fixes as well
Merged to master!

**Pull request merged**
