### PR TITLE
Add Trello 

### PR DESCRIPTION
**Pull request by jhevans**
I've started work on a Trello skin, I'm not that hot on css/sccs though so bear with me.  Having trouble darkening the boards tray without inverting the board colours in particular, they seem to be applied as in line style tags so not sure if it's even possible. Any help would be appreciated.

### CODE REVIEW

**Comment by theme1256** [comment]
Try this :)
.compact-board-tile-background[style="background-color: #0079BF;"] {
 	background-color: lighten(#0079BF, 5%) !important;
 }

Not sure if it'll work, but that would be my best guess to make it work :)

**Comment by theme1256** [comment]
Also you should change it from "full" to "in-development" :)

**Comment by jhevans** [comment]
Thanks, will get on it! :)

**Comment by jhevans** [comment]
Does anyone have any ideas on how to show the background colour chosen in Trello?  It seems like it should give an indication of which background colour was selected fairly prominently, though more subtly than the default Trello skins.  The pink background hurts my eyes.

I was thinking of trying a darkened version of the skin to the whole page, or maybe on the header bar or canvas only? What would be in keeping with what you're trying to achieve with Darkness?

**Comment by theme1256** [comment]
Just had a look and it looks like the board-color is set on the body tag, so if the previous worked, try:
body[style="background-color: rgb(0, 121, 191);"] {
background-color: lighten(rgb(0, 121, 191), 5%) !important;
}

**Comment by liorgrossman** [comment]
Hi John! Thanks for the Trello skin, awesome initiative 👍 
Thanks @theme1256 for the help here.
I'm merging this pull request into master so we can keep working on the Trello skin together.
Once finished I'll change it from "in-development" to "full" status.

**Pull request merged**
