### PR TITLE
Add JSFiddle

### PR DESCRIPTION
**Pull request by derekbtw**
Added JSFiddle to the list. Hope you like it.

One note: The 'Result' window changes to white when you hover over it allowing you to get a more accurate look at what you've made.

image

### CODE REVIEW

**Comment by liorgrossman** [comment]
Awesome initiative, thank you Derek! 👍 
Merged this into master

**Comment by derekbtw** [comment]
Very happy that you like it! I'll be doing some more, skinning websites is a good fun way to pass time I've found 🤓 👍

**Comment by liorgrossman** [comment]
Great! 😃 

Please pull from master:
```
git checkout master
git pull upstream master
```
I have fixed the location of the moon icon on JSFiddle (even when no dark theme is applied). It's sort of undocumented, but it's done in page.scss (which is loaded on all supported websites, even when no dark theme is applied).
See what I did here: https://github.com/liorgrossman/darkness/commit/7a7f88e8fd8b1af0303dc51794bac13937f4d47f

**Comment by derekbtw** [comment]
Oh, awesome! Thanks for the heads up!

**Pull request merged**
