### PR TITLE
Minor fixes on material theme

### PR DESCRIPTION
**Pull request by JavierOlazaran**
Some elements on the top bar where displayed with an awkward background

This how it looks today
OriginalMaterial

This is how it looks with the changes
ModifiedMaterial

### CODE REVIEW

**Comment by liorgrossman** [comment]
Looking good, thank you @JavierOlazaran 
Merged to master

**Comment by theme1256** [comment]
I feel like this was a bad merge!  
All he did has make everything transparent!  
Most other themes are broken now.

Facebook:  
image

Trello:
image

I'm goind to revert it and do a proper fix for the Google toolbars.

**Comment by liorgrossman** [comment]
Oh crap, I didn't see that one.
Thanks @theme1256

**Comment by JavierOlazaran** [comment]
So sorry about that

**Pull request merged**
