### PR TITLE
Fixes for new Gmail UI

### PR DESCRIPTION
**Pull request by lwojcik**
Fixing some minor annoyances with new Gmail interface (account info, labels, stars).

I put new Gmail rules in the same file as the ones for old Gmail. Is it okay or should I put them in a separate file?

### CODE REVIEW

**Comment by liorgrossman** [comment]
Thanks for this!

I don't see a problem putting it in the same file, as long as the tweaks don't break the old Gmail (many people use the old design).

Please revert to the old design temporarily and check if your scss changes break it. 
If they do, the easiest solution is *wrapping* all the new scss in a distinctive class that exists only in the new gmail. e.g. body.newgmail {}
If I recall correctly, that's what we did when YouTube upgraded to the new design, but many users were still using the old design.

**Comment by liorgrossman** [comment]
Hey @lwojcik - what's up? Need any help?

**Comment by lwojcik** [comment]
Thanks for asking. Everything is okay, had to switch my focus to 'real life' stuff for a bit. I'll be back to this soon.

**Comment by yuletide** [comment]
Have some fixes started here for the compose and reply views https://github.com/yuletide/darkness/tree/gmailfixes

A bit stumped on what to do with the bottom formatting bar, man the gmail HTML/CSS is a nightmare

**Comment by lwojcik** [comment]
So, uhm, hello from 2020.

I don't like leaving things unfinished but a lot of stuff happened since I opened that pull request. Most importantly, native dark themes in Gmail seem to be working good enough for me and I don't use Darkness for it.

I'm closing this PR as unresolved so that it doesn't haunt me at night as the only unresolved one.

**Pull request closed without merging**
