### PR TITLE
New themes and some fixes

### PR DESCRIPTION
**Pull request by theme1256**
Created a theme for CloudFlare and Google Docs.
Minor fixes for Google Inbox and Facebook Messenger.

### CODE REVIEW

**Comment by liorgrossman** [comment]
Awesome man! :sunglasses:
I can see what is missing in Cloudflare (based on the comments you put in cloudflare.scss).

What is still missing from Google Docs? 
Based on first impression, I can see the toolbar (where all the styling is) requires some work.

**Comment by theme1256** [comment]
Cloudflare doesn't need work, maybe some of the premium features.
I just thought I would need to do more work and created a lot of comments, but they weren't needed.

I felt the toolbar in docs to be done, but I never checked all the submenus, only the ones I knew used colors.

**Comment by liorgrossman** [comment]
Got it, cool.
I don't use Cloudflare, but the main page looks kinda inverted :)
https://www.cloudflare.com/

As for Google Docs, the toolbar is mostly invisible here (see screenshot below).
Are you fully committed / pushed?

**Comment by theme1256** [comment]
The cloudflare thing is because the use gradient background and I just didn't mind it, but I can take a look at it.
The Docs thing is because I fixed some icons on the docs homepage and didn't check the other sites, oops.

Yes I have pushed everything I have

**Pull request merged**
